### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by abdelrahmankhaled1412** [Mariosmsk/QChatGPT#4] opened 2023-02-16 15:58 UTC
Couldn't load plugin 'QChatGPT' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'openai'
can you make a video for this proplem ? 
Great Work by the way

**Comment by Gustry** [comment] 2023-02-20 09:51
This looks a duplicate of #1

**Comment by Mariosmsk** [comment] 2023-02-20 10:00
Hi all, I closed these issues, I think we solved them in the updated version of QChatGPT v0.2!
Thanks

fix #1

**Closed by Mariosmsk** 2023-02-20 10:00 UTC
